version: '3'

services:
  postgres:
    image: postgres:16
    container_name: paper_review_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paper_review_backend
    depends_on:
      - postgres
    environment:
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-postgres}
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:8081,http://frontend:8081
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paper_review_frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    ports:
      - "8081:8081"
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 