[project]
name = "openai-hackathon-wait"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kuba Kwiecien", email = "kwiscion@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.0.13",
]

[project.scripts]
openai-hackathon-wait = "openai_hackathon_wait:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.find]
packages = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
